module.exports = (sequelize, DataTypes) => {
    const incidencias = sequelize.define('incidencias', {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true, // generated by default as identity
        allowNull: false
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW
      },
      id_vivienda: {
        type: DataTypes.BIGINT,
        allowNull: false,
        references: {
          model: 'viviendas', // nombre tabla referenciada
          key: 'id'
        }
      },
      id_trabajador: {
        type: DataTypes.BIGINT,
        allowNull: false,
        references: {
          model: 'trabajadores',
          key: 'id'
        }
      },
      fecha_visita: {
        type: DataTypes.DATE, // timestamp without time zone
        allowNull: true
      },
      solucionada: {
        type: DataTypes.BOOLEAN,
        allowNull: true
      }
    }, {
      tableName: 'incidencias',
      timestamps: false
    });
  
    return incidencias;
  };