module.exports = (sequelize, DataTypes) => {
    const inquilinos = sequelize.define('inquilinos', {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true, // generated by default as identity
        allowNull: false
      },
      created_at: {
        type: DataTypes.DATE, // timestamp with time zone
        allowNull: false,
        defaultValue: DataTypes.NOW
      },
      nombre: {
        type: DataTypes.STRING,
        allowNull: false
      },
      apellidos: {
        type: DataTypes.STRING,
        allowNull: false
      },
      fecha_nacimiento: {
        type: DataTypes.DATEONLY, // solo fecha, sin hora
        allowNull: false
      },
      dni: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true // clave única
      }
    }, {
      tableName: 'inquilinos',
      timestamps: false
    });
  
    return inquilinos;
  };