module.exports = (sequelize, DataTypes) => {
    const trabajadores = sequelize.define('trabajadores', {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true, // generated by default as identity
        allowNull: false
      },
      created_at: {
        type: DataTypes.DATE, // timestamp with time zone
        allowNull: false,
        defaultValue: DataTypes.NOW
      },
      id_empresa: {
        type: DataTypes.BIGINT,
        allowNull: true,
        references: {
          model: 'empresas',
          key: 'id'
        },
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE'
      },
      nombre: {
        type: DataTypes.STRING,
        allowNull: true
      },
      apellidos: {
        type: DataTypes.STRING,
        allowNull: true
      },
      profesion: {
        type: DataTypes.STRING,
        allowNull: true
      }
    }, {
      tableName: 'trabajadores',
      timestamps: false
    });
  
    return trabajadores;
  };