module.exports = (sequelize, DataTypes) => {
  const viviendas = sequelize.define('viviendas', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      autoIncrement: true, // generated by default as identity
      allowNull: false
    },
    created_at: {
      type: DataTypes.DATE, // timestamp with time zone
      allowNull: false,
      defaultValue: DataTypes.NOW
    },
    direccion: {
      type: DataTypes.STRING,
      allowNull: true
    },
    escalera: {
      type: DataTypes.STRING,
      allowNull: true
    },
    piso: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    letra: {
      type: DataTypes.STRING,
      allowNull: true
    },
    habitaciones: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    metros_cuadrados: {
      type: DataTypes.BIGINT,
      allowNull: true
    },
    observaciones: {
      type: DataTypes.TEXT,
      allowNull: true
    }
  }, {
    tableName: 'viviendas',
    timestamps: false
  });

  return viviendas;
};