module.exports = (sequelize, DataTypes) => {
  const viviendas_inquilinos = sequelize.define('viviendas_inquilinos', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      autoIncrement: true, // generated by default as identity
      allowNull: false
    },
    fecha_entrada: {
      type: DataTypes.DATE, // timestamp without time zone
      allowNull: false,
      defaultValue: DataTypes.NOW
    },
    fecha_salida: {
      type: DataTypes.DATE, // timestamp without time zone
      allowNull: true
    },
    id_vivienda: {
      type: DataTypes.BIGINT,
      allowNull: true,
      references: {
        model: 'viviendas',
        key: 'id'
      }
    },
    id_inquilino: {
      type: DataTypes.BIGINT,
      allowNull: true,
      references: {
        model: 'inquilinos',
        key: 'id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE'
    }
  }, {
    tableName: 'viviendas_inquilinos',
    timestamps: false
  });

  return viviendas_inquilinos;
};